ASP.NET_MVC/Controllers/CreditController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Globalization;
using WebAppMVC.Models;
using WebAppMVC.ViewModels;

namespace WebAppMVC.Controllers
{
    public class CreditController : Controller
    {
        private readonly Serilog.ILogger _logger;
        private CreditModel _model;

        public CreditController(CreditModel model, Serilog.ILogger logger)
        {
            CultureInfo.CurrentCulture = new CultureInfo("en-US");
            _logger = logger;
            _model = model;
        }
        [HttpGet]
        public ActionResult Index()
        {
            _logger.Information("Open Home Page: /Credit/Index");
            return View(_model);
        }
        [HttpPost]
        public ActionResult Index(CreditModel model)
        {
            _logger.Information("Calculate Credit");
            model.CreditCalculate();

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            _logger.Error($"{HttpContext.Request.Path} {HttpContext.TraceIdentifier}");
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET_MVC/Controllers/DepositController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Globalization;
using WebAppMVC.Models;
using WebAppMVC.ViewModels;

namespace WebAppMVC.Controllers
{
    public class DepositController : Controller
    {
        private readonly Serilog.ILogger _logger;
        private DepositModel _model;

        public DepositController(DepositModel model, Serilog.ILogger logger)
        {
            CultureInfo.CurrentCulture = new CultureInfo("en-US");
            _logger = logger;
            _model = model;
        }
        [HttpGet]
        public ActionResult Index()
        {
            _logger.Information("Open Home Page: /Deposit/Index");
            return View(_model);
        }
        [HttpPost]
        public ActionResult Index(DepositModel model)
        {
            _logger.Information("Calculate deposit");
            model.DepositCalculate();
            return View(model);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            _logger.Error($"{HttpContext.Request.Path} {HttpContext.TraceIdentifier}");
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyCalculator_v4.0.styles.css" asp-append-version="true" />
    <link href="/calc_icon.ico" rel="shortcut icon" runat="server" type="image/x-icon" />
    <link href="/calc_icon.ico" rel="icon" runat="server" type="image/ico" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand navbar-bg border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <ul class="navbar-nav gap-3">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">MyCalculator_v4.0</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Graph">Graph</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Credit" asp-action="Index">Credit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Deposit" asp-action="Index">Deposit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div>
            &copy; 2023 - MyCalculator_v4.0(Web)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>